### ISSUE TITLE
There is no "Approvals - Start an approval" action

### ISSUE THREAD

**Issue by nguyenlamlll** [MicrosoftDocs/power-automate-docs#140]
As of the time of writing, the action "Approvals - Start an approval" seems to no longer exist.
Instead, there are:
- Create an approval (V2)
- Start and wait for an approval 
- Start and wait for an approval (V2)
- Wait for an approval (v2)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f51e26d-e8cd-2152-45a2-bd23d13fb3b2
* Version Independent ID: 30768baf-8dd7-d64c-aec2-f500fbbe1e78
* Content: [Easily Automate approval workflows. - Microsoft Flow](https://docs.microsoft.com/en-us/flow/modern-approvals#add-a-trigger)
* Content Source: [flow-docs/modern-approvals.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/modern-approvals.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by tagiles** [comment]
I am being told a CDS (the database on which this is run) needs a license from Plan 1 or Plan 2, a level higher than the license provided with Office Premium 365, which costs $5 / person / month, however only 1 user requires it to allow approvals / Flow to run again. Note some flows still run without a CDS database / license level. (Create a file --> Email)

I believe the instructions above to be out of date.

**Comment by nguyenlamlll** [comment]
Indeed, my license is Microsoft Flow for Office 365 Free.
For more information, I can still achieve a flow with "Start an approval" action if I use [the template](https://asia.flow.microsoft.com/en-us/galleries/public/templates/906bdcc238bb49f19879ab62a88f3aa7/request-manager-approval-for-leave-requests/).

**Comment by huayue21** [comment]
@nguyenlamlll did you find it now?

**Comment by tagiles** [comment]
I had Microsoft Office 365 version also @Lam Le, and was told I had to
purchase a Power Apps license to use Flow. Sometime this spring all our
flows had stopped without warning from microsoft (it was buried in a update
text in the spring) when Flow was paywalled. I left Office for Google
GSuite and haven't been happier since. I am using Approvals through Google
Drive and it is fantastic - more options than Flow such as setting
deadlines/etc.

**Comment by nguyenlamlll** [comment]
@huayue21: In a way. 
The options I can find right now are as the picture below. 
![image](https://user-images.githubusercontent.com/20963684/67917415-86cc9c80-fbcb-11e9-9eb6-55dece754bd7.png)

The picture for step 3 in Add an approval action section is a bit outdated.

**Comment by tagiles** [comment]
Hi Lam

I found the UI did not change at all, but the underlying functions stopped
working. I could still setup a flow and implement it on a schedule. There
was no warnings or any indication at all, be through documentation or the
UI, that the functions were paywalled. Support themselves did not know that
these functions had been moved under a PowerApps license, it took a couple
days of checking on their end to get back to me.

What error are you getting? I got a cryptic error
'ViralServicePlanUnavailable'.

See this thread - the same confusion:
https://powerusers.microsoft.com/t5/Building-Flows/Approval-flows-stopped-working-and-I-can-no-longer-save-new/td-p/312874


Message #7 - this happened at the time the CDS upgrade warning was
released, and now you need a CDS license which powers flow behind the
scenes, and now CDS is under 'P2' (POwerApps) license.

Flow has been paywalled, 100% - it took me weeks of talking with support
for them to confirm it. I needed to buy a PowerApps flow license but
because my Office provider was GoDaddy, they couldnt figure out how I would
purchase it.

I am much happier w google - must stress this again.

Contact support, you will need a PowerApps license to use Flow.

**Comment by khadimali** [comment]
I have added the P2 trial license in office 365 tenant, still not able to see "Approvals - Start an approval" action. What I can see is "Start and wait for approval". And that action doesn't have "Response" item in Dynamic Content pane. :-(

**Comment by MSFTMan** [comment]
@khadimali Thanks for using Power Automate. The doc needs to be updated. We are in the process of updating it. Yes, you can use **Start and wait for approval**.

**Comment by kk-sdsu** [comment]
I have several Flows that I have been working on for months for automating vacation, travel and purchase requests that have been suddenly broken by this licensing change, scheduled for go-live by Jan 1, 2020. I had to let my CIO know that I couldn't deliver as promised, luckily before the announcement was sent out. This is very frustrating, and has made me lose confidence in this platform and Microsoft's ability to professionally support it. Your documentation has been out of date for over a month. This change should have been well documented and communicated. Please, update your documentation. I see comments above indicating that all that is needed is Flow Plan 2, or PowerApps Plan 2, both of which are applied to the account running the Flows, and yet they do not work. I don't even know what I need to do, and I'm looking like a fool. Shame on me for trusting you.

**Comment by v-aangie** [comment]
The content, including the screenshot, have been updated with Start and wait for approval. Closing this issue.
