### ISSUE TITLE
dammit!! docs never tell the story

### ISSUE THREAD

**Issue by urklnme** [MicrosoftDocs/power-automate-docs#308]
so not well done.  WhereTF can I create an action?  under solutions only?  so tired of half-assed docs.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46309753-0233-f86b-1d82-8c0619c69c88
* Version Independent ID: 4ee6d841-f58f-599d-3e9f-cd91a56a4609
* Content: [Configure actions for workflows in Power Apps - Power Automate](https://docs.microsoft.com/en-us/power-automate/configure-actions)
* Content Source: [articles/configure-actions.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/configure-actions.md)
* Service: **flow**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by MSFTMan** [comment]
@urklnme Thanks for reporting this issue. We'll check with the product team and update the docs.

**Comment by Dean-Haas** [comment]
Hi @urklnme. This doc has been updated since you left feedback. The information you are tallking about is covered ion the Create an Action section, as well as here: https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/invoke-custom-actions-workflow-dialog

Thanks for submitting docs feedback.
