### ISSUE TITLE
What is the "Active Directory entry"?

### ISSUE THREAD

**Issue by afratila** [MicrosoftDocs/power-automate-docs#334]
For the Get Group Members activity, it takes inputs 
- "Parent directory entry" which is of type Active Directory entry, and 
- "Distinguished name" which is a string. 

What are these? I am finding no information online about what an "Active directory **entry**" or "distinguished name" is, and no fields resembling those names are found in the Azure Portal properties for the AAD. Where can I find these values?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8c766f1-fe28-e52a-f5d8-f01b54ad8e84
* Version Independent ID: ffecb81c-d417-bb31-bf35-8f2a213ad134
* Content: [Active Directory - Power Automate](https://docs.microsoft.com/en-us/power-automate/ui-flows/desktop/actions-reference/activedirectory#getgroupmembers)
* Content Source: [articles/ui-flows/desktop/actions-reference/activedirectory.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/ui-flows/desktop/actions-reference/activedirectory.md)
* Service: **flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by Dean-Haas** [comment]
Hi @afratila . Thanks for submitting docs feedback. It looks like you are wanting help with a technology question, rather than reporting an issue with the docs. A better place to post your question is in the [Power Automate community](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity) where your question will be seen by power users, rather than writers and editors.  Thanks!
