### ISSUE TITLE
URL parameter, with an URL encoded string

### ISSUE THREAD

**Issue by Joakim3** [MicrosoftDocs/power-automate-docs#435]
Regarding the URL parameter, I get a Syntax error if I have an URL encoded string (containing %20 for a space as an example)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10a843a8-7e9e-53ef-6955-bd22e62f8e8a
* Version Independent ID: fd74890d-8fd9-3354-5584-3cba236902c8
* Content: [Web | Microsoft Docs - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/web#invokewebservicebase)
* Content Source: [articles/desktop-flows/actions-reference/web.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/desktop-flows/actions-reference/web.md)
* Service: **flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
Hello @Joakim3 thank you for using Power Automate Desktop. In this case Power Automate Desktop thinks that %20 is a variable. Try using %%20 in order to escape this. Please note, that you may find responses to your questions in the [Power Automate community](https://preview.flow.microsoft.com/en-us/support/) where technical experts can respond to such technical questions.
