### ISSUE TITLE
When I execute action "stop service",I got error

### ISSUE THREAD

**Issue by tripod31** [MicrosoftDocs/power-automate-docs#440]
When I execute action "stop service",I got error.
I guess its permission issue.
In case  that I execute PAD as administrator,I also got same error.
I log in as administrator user.I can stop service in "service" administration GUI.
https://imgur.com/SWWYKRy

**Comment by mariosleon** [comment]
Hello @tripod31, thank you for using Power Automate Desktop. As this question is more of a technical issue, rather than a documentation issue, I would kindly ask you pose your question to the [Power Automate community](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity) where technical experts can assist you.
