### ISSUE TITLE
When i turn off the power automate for a test entry in my sharepoint list and once i turned on back the power automate triggered the test entries as well.

### ISSUE THREAD

**Issue by sonycherk** [MicrosoftDocs/power-automate-docs#546]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19c08b2-1f6e-0430-6074-18d64d6c8b17
* Version Independent ID: fc9595bd-0d84-ecad-17de-dd3818a6cb3b
* Content: [Turn flows on or off - Power Automate](https://docs.microsoft.com/en-us/power-automate/disable-flow)
* Content Source: [articles/disable-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/disable-flow.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @Puyush6889
* Microsoft Alias: **kapolepa**

**Comment by DavidPaf** [comment]
This because the SharePoint connector using Polling trigger: 

_If you turned off your flow and then turned it back on, depending on your trigger type, your old triggers may be processed.

A polling trigger periodically makes a call to your service to look for new data, whereas a Webhook trigger responds to a push of new data from the service._ 

https://docs.microsoft.com/en-us/power-automate/triggers-troubleshoot#my-trigger-is-firing-for-old-events

Mitigation is to use Trigger Condition, see details here: https://mspower.herokuapp.com/en/blog/flow-when-item-created-or-modified-triggers-old-events/

**Comment by MSFTMan** [comment]
@sonycherk Thanks for using Power Automate. We've updated the doc to inform makers that when a flow is turned on, old events may be activated and cause the flow to run.
