### ISSUE TITLE
Getting error: Get-DesktopFlowModules : The term 'Get-DesktopFlowModules' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is  correct and try again.

### ISSUE THREAD

**Issue by ashmsport** [MicrosoftDocs/power-automate-docs#671]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b153bd2d-0c9a-2982-5cee-c271bd814388
* Version Independent ID: c58d38f5-5a7b-dabb-c75b-c38108139bbe
* Content: [Introduction to data loss prevention (DLP) policies. - Power Automate](https://docs.microsoft.com/en-us/power-automate/prevent-data-loss)
* Content Source: [articles/prevent-data-loss.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/prevent-data-loss.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by mariosleon** [comment]
Hello @ashmsport, Thank you for using Power Automate. Please note that in order to run this command you would need to have the latest Powershell installed, v. 2.0.142 on your machine. You may ask technical questions in the [Power Automate community](https://preview.flow.microsoft.com/en-us/support/) where technical experts can respond to your questions and suggest solutions.
